### ISSUE TITLE
[IOS] Theme Switch Animation + Drawer Navigator

### ISSUE THREAD

**Issue by vsnaichuk** [WadhahEssam/react-native-theme-switch-animation#11]
Hello,

Thank you for this excellent library!

I have noticed an inconsistency across platforms when using it with DrawerNavigator from react-navigation. I have attached a screen recording that captures the issue.

I would greatly appreciate any help

https://github.com/WadhahEssam/react-native-theme-switch-animation/assets/29066432/013bbb0c-fa3a-4e63-a0c9-c78c13ce8e5a

**Comment by WadhahEssam** [comment]
This is interesting thank you @vsnaichuk for pointing it, I will look into it whenever I have time. can you provide me of what you are using for the Drawer

**Comment by vsnaichuk** [comment]
Thank you for your response @WadhahEssam! 
I created a simple repro example (https://github.com/vsnaichuk/theme-switch-drawer-repro) and noticed that the issue only occurs when using `drawerType: 'back'`. When using other types of drawer (slide or front), the issue does not occur.
