### ISSUE TITLE
Support for node 16?

### ISSUE THREAD

**Issue by ThalesBMC** [WadhahEssam/react-native-theme-switch-animation#2]
I would love that the minimum requirements of this library was node v16

**Comment by WadhahEssam** [comment]
@ThalesBMC what is the issue that you get when using/installing it, so I can confirm this issue is gone

**Comment by ThalesBMC** [comment]
> @ThalesBMC what is the issue that you get when using/installing it, so I can confirm this issue is gone

@WadhahEssam 
When I try to run yarn install on my project, which uses v16, it displays an error indicating incompatibility because the minimum requirement for your project is Node >= 18.
"engines": {
    "node": ">= 18.0.0"
  },
  
  Error:
  error react-native-theme-switch-animation@0.4.1: The engine "node" is incompatible with this module. Expected version ">= 18.0.0". Got "16.16.0"

**Comment by WadhahEssam** [comment]
got it 👍

**Comment by WadhahEssam** [comment]
done
