### ISSUE TITLE
[iOS] UI issue. The borders flickering with the shadow during transition.

### ISSUE THREAD

**Issue by tr3v3r** [WadhahEssam/react-native-theme-switch-animation#3]
Hello. First of all thanks for such a cool library!

I've just installed and checked the animation and everything works fine, but I noticed weird behavior. When an element has a border style, it flickers with a strange shadow around it.

Steps to reproduce:

1) Add any view with a border style on the screen
2) Stay on this screen and try to switch theme with animation

https://github.com/WadhahEssam/react-native-theme-switch-animation/assets/23724142/1ddaf7d4-bf70-4004-a05d-4fadfb53672e

**Comment by WadhahEssam** [comment]
Hello @tr3v3r can you post your code for this section please, I tried to reproduce it but I couldn't.





here is what I tried 
<img width="404" alt="Screenshot 2023-11-10 at 5 34 26 PM" src="https://github.com/WadhahEssam/react-native-theme-switch-animation/assets/24798045/f4e9d8ef-12c9-4cb4-9cb9-e83a53dff681">

https://github.com/WadhahEssam/react-native-theme-switch-animation/assets/24798045/fd861bca-3c33-4272-85d3-9e273866b689



also tried adding shadow view 

<img width="388" alt="Screenshot 2023-11-10 at 5 35 40 PM" src="https://github.com/WadhahEssam/react-native-theme-switch-animation/assets/24798045/24da1212-a239-4666-a9b1-232a9e1965e2">

and still couldn't get this effect

**Comment by gorbypark** [comment]
I've noticed this behaviour as well, but on the stock react-navigation bottom bar.  You can see a shadow the pops in and then pop out again during the animation.

https://github.com/WadhahEssam/react-native-theme-switch-animation/assets/19569469/c3bd43f8-8a3a-4327-b4f5-44bab4216a5f

**Comment by gorbypark** [comment]
I've been able to isolate it to the `borderTopWidth` of the stock bottom tab bar of react-navigation.  Here it is with a borderWidth of 1 and color red, which makes it easier to see!

```js
   <Tabs
      screenOptions={{
        tabBarStyle: {
          borderTopColor: "red",
          borderTopWidth: 1,
        },
      }}
```
    
Setting `borderTopWidth: 0` makes the issue go away.

https://github.com/WadhahEssam/react-native-theme-switch-animation/assets/19569469/1ac8e070-78cb-459a-9310-5c68f14535b7

**Comment by gorbypark** [comment]
Sorry for the barrage of updates, but weirdly enough, if you set a border width on anything, this issue happens, but if you set a borderRadius, it goes away.

https://github.com/WadhahEssam/react-native-theme-switch-animation/assets/19569469/99145861-84d6-4bf5-a190-4e11b2ee4a6b

**Comment by WadhahEssam** [comment]
Wow this is really interesting, as you might know the package is just taking a snapshot, it might be worth it to investigate why this artifact is taking place with these scenarios, Thank you guys

**Comment by WadhahEssam** [comment]
Added a section to the docs on how to solve it, thank you guys
