### ISSUE TITLE
Add reverse circle

### ISSUE THREAD

**Issue by arasrezaei** [WadhahEssam/react-native-theme-switch-animation#4]
Hi there,
thanks for this handy library.
i think it would be cool if we can do reverse circle so for example for light to dark we have regular circle, and for dark to light reverse circle would be nice.

**Comment by WadhahEssam** [comment]
hello @arasrezaei  this is already included in the library here is an example 


 ```
 switchTheme({
  switchThemeFunction: () => {
    setTheme(theme === 'light' ? 'dark' : 'light'); // your switch theme function
  },
  animationConfig: {
    type: theme === 'light' ?  'circular' : 'inverted-circular',
    duration: 900,
    startingPoint: {
      cxRatio: 0.5,
      cyRatio: 0.5
    }
  },
});
```
