### ISSUE TITLE
Issue with Package Compatibility in React Native when using BlurView in Components

### ISSUE THREAD

**Issue by ElSierra** [WadhahEssam/react-native-theme-switch-animation#6]
I have encountered an issue . The problem arises when the view includes the BlurView component as part of its views. The App Crashes with an Error.  `Radius out of range (0<r<=25)`

**Comment by WadhahEssam** [comment]
@ElSierra  what library do you use? is it expo-blur?

**Comment by ElSierra** [comment]
Yes, expo-blur

**Comment by ElSierra** [comment]
> @ElSierra  what library do you use? is it expo-blur? 

Yes expo-blur

**Comment by WadhahEssam** [comment]
sorry for being too late for this. can you please test it again with latest version of both this library and expo-blur, because I tested it and had no issues

**Comment by WadhahEssam** [comment]
sorry for being too late for this. can you please test it again with latest version of both this library and expo-blur, because I tested it and had no issues

**Comment by ElSierra** [comment]
Thanks, I'll give it a try

**Comment by ElSierra** [comment]
@WadhahEssam still doesn't work with expo-blur on android

**Comment by WadhahEssam** [comment]
can you create a sample reproduction repository, would really appreciate it as I just tested it yesterday and it worked
