### ISSUE TITLE
 Error: The package 'react-native-theme-switch-animation' doesn't seem to be linked

### ISSUE THREAD

**Issue by ThalesBMC** [WadhahEssam/react-native-theme-switch-animation#7]
Anyone having this problem when trying to add the package to a project?

node: v16.
React Native: 0.63.4 (I think this is probably the problem)

 Error: The package 'react-native-theme-switch-animation' doesn't seem to be linked. Make sure: 

- You rebuilt the app after installing the package
- You are not using Expo Go

ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)

**Comment by WadhahEssam** [comment]
that is very old version, it could be the problem, but are you sure you did the pod install step?

**Comment by ThalesBMC** [comment]
> that is very old version, it could be the problem, but are you sure you did the pod install step?

Yep, It's probably the old version. 

When I update to a new version I will test again.

**Comment by ThalesBMC** [comment]
@WadhahEssam,

I've identified a solution for manual linking of the `react-native-theme-switch-animation` library in older versions, which is necessary due to the use of the turbo package. Here are the steps for both iOS and Android platforms:

## iOS:
1. **Update your `Podfile`** with the following line:
   ```ruby
   pod 'react-native-theme-switch-animation', :path => '../node_modules/react-native-theme-switch-animation'
   
   
## Android:

Modify your android/app/build.gradle file to include:
```
implementation project(':react-native-theme-switch-animation')
```

Update your settings.gradle file with:
```
include ':react-native-theme-switch-animation'
project(':react-native-theme-switch-animation').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-theme-switch-animation/android')

```

MainApplication.java, import and add ThemeSwitchAnimationPackage to the packages list:
```
import com.themeswitchanimation.ThemeSwitchAnimationPackage;
packages.add(new ThemeSwitchAnimationPackage());

```

**Comment by WadhahEssam** [comment]
@ThalesBMC that is wild, I remember there was something like `yarn link [library-name]` it was used to link native android libs, is that still an option,

Thanks Thales 👌

**Comment by harisuperpe** [comment]
@ThalesBMC How can I do the same for Kotlin. Facing this issue in RN 0.76.1
